name: CI

language: python
dist: xenial
python:
  - "^3.7"

stages:
  - Quality
  - Testing

before_install:
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: Quality
      name: lint
      script: make lint
    - name: type
      script: make type
    - name: tests
      script: make tests
    - stage: Testing
      name: pytest
      script: make mtest

after_success:
  poetry run coveralls