name: lint-test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: | 
          make install
          make lint
          make mtest
